{
 "title": "load test",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PUBLISH ERRORS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "publish_error_total{priority=\"high\"}",
     "legendFormat": "high"
    },
    {
     "expr": "publish_error_total{priority=\"medium\"}",
     "legendFormat": "medium"
    },
    {
     "expr": "publish_error_total{priority=\"low\"}",
     "legendFormat": "low"
    }
   ]
  },
  {
   "title": "QUEUE SIZE",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "queue_size{queue=\"loadTestPriorityQueue_high\"}",
     "legendFormat": "high"
    },
    {
     "expr": "queue_size{queue=\"loadTestPriorityQueue_medium\"}",
     "legendFormat": "medium"
    },
    {
     "expr": "queue_size{queue=\"loadTestPriorityQueue_low\"}",
     "legendFormat": "low"
    }
   ]
  },
  {
   "title": "PROCESSED MESSSAGES",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "processed_message_total{priority=\"low\"}",
     "legendFormat": "low"
    },
    {
     "expr": "processed_message_total{priority=\"medium\"}",
     "legendFormat": "medium"
    },
    {
     "expr": "processed_message_total{priority=\"high\"}",
     "legendFormat": "high"
    }
   ]
  }
 ]
}